### ISSUE TITLE
$compile:nonassign: Expression 'undefined' in attribute 'campaign' used with directive 'contributionFeedback' is non-...

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1411]
https://sentry.io/social-apps-lab/appcivist-pb-client/issues/747727429/?referrer=github_plugin

```
$compile:nonassign: Expression 'undefined' in attribute 'campaign' used with directive 'contributionFeedback' is non-assignable!
  at None (/1.5.9/$compile/nonassign)
  at None (/scripts/ui.js:2:765834)
  at parentSet (/scripts/ui.js:2:850355)
  at parentValueWatch (/scripts/ui.js:2:850684)
  at fn (/scripts/ui.js:2:897758)
...
(5 additional frame(s) were not displayed)

$compile:nonassign: Expression 'undefined' in attribute 'campaign' used with directive 'contributionFeedback' is non-assignable!
```

**Comment by yolile** [comment]
no reproducible and there are not current similar issues in the sentry
