### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1412]
https://sentry.io/social-apps-lab/appcivist-pb-client/issues/798470723/?referrer=github_plugin

```
TypeError: Cannot read property 'filter' of undefined
  at FormCtrl.isInWg (/scripts/app.js:2:490251)
  at fn0 (/scripts/ui.js:2:996521)
  at None (/scripts/ui.js:2:895363)
  at Scope.$digest (/scripts/ui.js:2:911203)
  at ChildScope.$apply (/scripts/ui.js:2:913648)
...
(4 additional frame(s) were not displayed)
```

**Comment by yolile** [comment]
still an issue, check sentry for details https://sentry.io/organizations/social-apps-lab/issues/868832721/?project=1309417&query=is%3Aunresolved+TypeError&statsPeriod=14d
