### ISSUE TITLE
Fix grunt build

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#509]
```
Running "uglify:dist" (uglify) task
JS_Parse_Error {
  message: 'Unexpected token punc «(», expected punc «:»',
  filename: 'app.js',
  line: 8396,
  col: 19,
  pos: 318569,
  stack: 'Error\n    at new JS_Parse_Error (/Users/cdparra/Projects/appcivist/appcivist-pb-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:196:18)\n    at js_error (/Users/cdparra/Projects/appcivist/appcivist-pb-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:204:11)\n    at croak (/Users/cdparra/Projects/appcivist/appcivist-pb-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:680:9)\n    at token_error (/Users/cdparra/Projects/appcivist/appcivist-pb-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:688:9)\n    at expect_token (/Users/cdparra/Projects/appcivist/appcivist-pb-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:701:9)\n    at expect (/Users/cdparra/Projects/appcivist/appcivist-pb-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:704:36)\n    at /Users/cdparra/Projects/appcivist/appcivist-pb-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:1257:13\n    at /Users/cdparra/Projects/appcivist/appcivist-pb-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:727:24\n    at expr_atom (/Users/cdparra/Projects/appcivist/appcivist-pb-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:1187:35)\n    at maybe_unary (/Users/cdparra/Projects/appcivist/appcivist-pb-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:1363:19)' }
>> Uglifying source ./dist/scripts/app.js failed.
Warning: Uglification failed.
Unexpected token punc «(», expected punc «:». 
Line 8396 in ./dist/scripts/app.js
 Use --force to continue.

```

**Comment by cdparra** [comment]
[Apparently, uglify cannot parse ES6](https://github.com/webpack/webpack/issues/2972#issuecomment-261705632)
[A solution maybe?](https://www.npmjs.com/package/babel-plugin-uglify)

**Comment by jorgeramirez** [comment]
@cdparra the problem was that `copy:dist` task was overriding files that babel already processed.
